### ISSUE TITLE
1028 格式错误

### ISSUE THREAD

**Issue by wenjie1991** [xairry/PAT-Basic#7]
![image](https://user-images.githubusercontent.com/6602710/33795943-cc801fc0-dd25-11e7-8139-9068c275b39c.png)

**Comment by xairry** [comment]
![qq 20180305194312](https://user-images.githubusercontent.com/16918292/36973361-9c538672-20ad-11e8-84e9-bdba8ebd91fb.png)
有可能没有有效人数。
